name: eventora_app
description: Eventora - Smart Event Planning and Venue Management Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_chat_ui: ^1.6.9
  image_picker: ^1.0.4
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  timeago: ^3.5.0
  flutter_local_notifications: ^16.0.0+1
  share_plus: ^7.1.0
  connectivity_plus: ^5.0.1
  introduction_screen: ^3.1.11
  table_calendar: ^3.0.9
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_markdown: ^0.6.18
  webview_flutter: ^4.4.2
  file_picker: ^6.0.0
  dotted_border: ^2.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"